name: hexlet-lint
on: push
jobs:
  lint:
   runs-on: ubunty-latest
    steps:
      - name: 'Install_dependencies'
        run: | 
          pip install poetry
          make install
      - name: 'Run-linter'
        run: make lint