name: hexlet-lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: 'Install_dependencies'
        run: | 
          pip install poetry
          make install
      - name: linter start
        run: make lint